changelog:
  repository: spring-cloud/[fill in]
  sections:
    - title: ":star: New Features"
      labels: [ "enhancement" ]
    - title: ":lady_beetle: Bug Fixes"
      labels: [ "bug" ]
    - title: ":notebook_with_decorative_cover: Documentation"
      labels: [ "documentation" ]
    - title: ":hammer: Dependency Upgrades"
      labels: [ "dependencies" ]
    - title: ":heavy_check_mark: Tasks"
      labels: [ "task" ]
  contributors:
    exclude:
      names: [ "dependabot", "ryanjbaxter", "OlgaMaciaszek", "spencergibb", "marcingrzejszczak", "jonatan-ivanov", "dsyer", "olegz", "cppwfs", "mminella", "sobychacko", "onobc"]
